const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      images: '/images/p1.jpg',
      price: 120,
      countInStock: 19,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      images: '/images/p2.jpg',
      price: 120,
      countInStock: 19,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'Adidas Slim Pant',
      slug: 'Adidas-slim-pant',
      category: 'Shirts',
      images: '/images/p3.jpg',
      price: 120,
      countInStock: 19,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
    {
      name: 'Adidas fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Shirts',
      images: '/images/p4.jpg',
      price: 120,
      countInStock: 19,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirts',
    },
  ],
};

export default data;
